# Generated by Django 2.2.10 on 2021-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210719_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
